"""Fail-closed canonical CPU execution profiles for quality evaluations."""
from __future__ import annotations

import hashlib
import json
import os
import platform
import random
import re
import threading
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn.functional as F

LEGACY_CANONICAL_CPU_RUNTIME_VERSION = "toy-quality-canonical-cpu-runtime/1.0"
CANONICAL_CPU_RUNTIME_VERSION = "toy-quality-canonical-cpu-runtime/1.1"
HARDWARE_FINGERPRINT_VERSION = "toy-quality-cpu-hardware-fingerprint/1.0"

CANONICAL_THREAD_ENVIRONMENT = {
    "OMP_NUM_THREADS": "1",
    "MKL_NUM_THREADS": "1",
    "OPENBLAS_NUM_THREADS": "1",
    "NUMEXPR_NUM_THREADS": "1",
}
CANONICAL_EXECUTION_ENVIRONMENT = {
    **CANONICAL_THREAD_ENVIRONMENT,
    "ATEN_CPU_CAPABILITY": "default",
    "MKL_CBWR": "COMPATIBLE",
}

# This hash is generated by ``canonical_execution_sentinel_hash``. It is sealed to
# the supported runtime path and intentionally does not encode host identity.
CANONICAL_EXECUTION_SENTINEL_SHA256 = (
    "sha256:75333bd70721e7247ba71f8321801bbb99ec883a1b96311dee9c45edc49d0d1b"
)

_CONFIGURATION_LOCK = threading.Lock()
_CONFIGURED = False


def _sha256_bytes(value: bytes) -> str:
    return "sha256:" + hashlib.sha256(value).hexdigest()


def _canonical_json_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")


def _tensor_hashes(values: dict[str, torch.Tensor]) -> str:
    digest = hashlib.sha256()
    for name in sorted(values):
        tensor = values[name].detach().cpu().contiguous()
        digest.update(name.encode("utf-8") + b"\0")
        digest.update(str(tensor.dtype).encode("ascii") + b"\0")
        digest.update(_canonical_json_bytes(list(tensor.shape)) + b"\0")
        digest.update(tensor.numpy().tobytes())
    return "sha256:" + digest.hexdigest()


def canonical_execution_sentinel_hash() -> str:
    """Exercise representative forward, backward, clipping, and AdamW CPU paths."""
    left = (
        (torch.arange(0, 48 * 64, dtype=torch.float32).reshape(48, 64) % 37) - 18
    ) / 17
    right = (
        (torch.arange(0, 64 * 40, dtype=torch.float32).reshape(64, 40) % 29) - 14
    ) / 13
    bias = ((torch.arange(40, dtype=torch.float32) % 11) - 5) / 7
    left.requires_grad_(True)
    right.requires_grad_(True)
    bias.requires_grad_(True)

    addmm = torch.addmm(bias, left, right)
    normalized = F.layer_norm(addmm, (addmm.shape[-1],))
    probabilities = torch.softmax(normalized[:, :17], dim=-1)
    loss = (
        probabilities.square().sum()
        + normalized[:, 17:].sin().mean()
        + addmm[:, ::3].cos().mean()
    )
    loss.backward()
    raw_gradients = {
        "left": left.grad.detach().clone(),
        "right": right.grad.detach().clone(),
        "bias": bias.grad.detach().clone(),
    }
    gradient_norm = torch.nn.utils.clip_grad_norm_([left, right, bias], 1.0)
    clipped_gradients = {
        "left": left.grad.detach().clone(),
        "right": right.grad.detach().clone(),
        "bias": bias.grad.detach().clone(),
    }

    parameter = torch.nn.Parameter(
        ((torch.arange(257, dtype=torch.float32) % 23) - 11) / 19
    )
    parameter.grad = (
        ((torch.arange(257, dtype=torch.float32) % 31) - 15) / 29
    )
    optimizer = torch.optim.AdamW(
        [parameter],
        lr=3e-4,
        betas=(0.9, 0.95),
        eps=1e-8,
        weight_decay=0.01,
        foreach=False,
        fused=False,
    )
    optimizer.step()
    state = optimizer.state[parameter]

    return _tensor_hashes(
        {
            "addmm": addmm,
            "normalized": normalized,
            "probabilities": probabilities,
            "loss": loss,
            "raw_gradient_left": raw_gradients["left"],
            "raw_gradient_right": raw_gradients["right"],
            "raw_gradient_bias": raw_gradients["bias"],
            "gradient_norm": gradient_norm,
            "clipped_gradient_left": clipped_gradients["left"],
            "clipped_gradient_right": clipped_gradients["right"],
            "clipped_gradient_bias": clipped_gradients["bias"],
            "adamw_exp_avg": state["exp_avg"],
            "adamw_exp_avg_sq": state["exp_avg_sq"],
            "adamw_parameter": parameter,
        }
    )


def _torch_build_configuration() -> str:
    return "\n".join(
        line.rstrip() for line in torch.__config__.show().strip().splitlines()
    )


def _python_build_fingerprint() -> dict[str, object]:
    build_number, build_date = platform.python_build()
    return {
        "implementation": platform.python_implementation(),
        "version": platform.python_version(),
        "compiler": platform.python_compiler(),
        "build_number": build_number,
        "build_date": build_date,
    }


def _read_os_release() -> dict[str, str]:
    path = Path("/etc/os-release")
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if "=" not in raw_line:
            continue
        key, value = raw_line.split("=", 1)
        values[key] = value.strip().strip('"')
    return {key: values[key] for key in sorted(values)}


def _read_cpu_information() -> dict[str, object]:
    path = Path("/proc/cpuinfo")
    text = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
    first_block = text.split("\n\n", 1)[0]
    fields: dict[str, str] = {}
    for line in first_block.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        fields[key.strip()] = " ".join(value.split())
    raw_flags = fields.get("flags") or fields.get("Features") or ""
    flags = sorted(set(raw_flags.split()))
    capability_names = (
        "sse2",
        "avx",
        "avx2",
        "avx512f",
        "avx512dq",
        "avx512bw",
        "avx512vl",
        "fma",
    )
    return {
        "vendor": fields.get("vendor_id") or fields.get("CPU implementer"),
        "family": fields.get("cpu family"),
        "model": fields.get("model"),
        "stepping": fields.get("stepping"),
        "model_name": fields.get("model name") or fields.get("Processor"),
        "microcode": fields.get("microcode"),
        "logical_cpu_count": os.cpu_count(),
        "flags_sha256": _sha256_bytes("\n".join(flags).encode("ascii", errors="ignore")),
        "capabilities": {name: name in flags for name in capability_names},
    }


def _runner_metadata() -> dict[str, object]:
    names = (
        "RUNNER_OS",
        "RUNNER_ARCH",
        "RUNNER_ENVIRONMENT",
        "ImageOS",
        "ImageVersion",
        "AZURE_REGION",
    )
    return {name: os.environ.get(name) for name in names}


def canonical_cpu_runtime_fingerprint() -> dict[str, object]:
    build_configuration = _torch_build_configuration()
    return {
        "profile_version": CANONICAL_CPU_RUNTIME_VERSION,
        "deterministic_algorithms_enabled": torch.are_deterministic_algorithms_enabled(),
        "deterministic_warn_only_enabled": (
            torch.is_deterministic_algorithms_warn_only_enabled()
        ),
        "torch_num_threads": torch.get_num_threads(),
        "torch_num_interop_threads": torch.get_num_interop_threads(),
        "mkldnn_enabled": torch.backends.mkldnn.enabled,
        "cpu_dispatch_capability": torch.backends.cpu.get_cpu_capability(),
        "mkl_available": torch.backends.mkl.is_available(),
        "openmp_available": torch.backends.openmp.is_available(),
        "torch_build_config_sha256": _sha256_bytes(build_configuration.encode("utf-8")),
        "execution_sentinel_sha256": canonical_execution_sentinel_hash(),
        **{name: os.environ.get(name) for name in CANONICAL_EXECUTION_ENVIRONMENT},
    }


def observed_runtime_and_hardware() -> dict[str, object]:
    """Collect stable host evidence without hostname, process IDs, or timestamps."""
    runtime = canonical_cpu_runtime_fingerprint()
    observed = {
        "os": {
            "system": platform.system(),
            "release": platform.release(),
            "version": platform.version(),
            "machine": platform.machine(),
            "architecture": platform.architecture()[0],
            "os_release": _read_os_release(),
        },
        "cpu": _read_cpu_information(),
        "runner": _runner_metadata(),
        "python": _python_build_fingerprint(),
        "pytorch": {
            "version": torch.__version__,
            "cuda_version": torch.version.cuda,
            "build_configuration": _torch_build_configuration(),
            "build_configuration_sha256": runtime["torch_build_config_sha256"],
            "cpu_dispatch_capability": runtime["cpu_dispatch_capability"],
            "mkl_available": runtime["mkl_available"],
            "openmp_available": runtime["openmp_available"],
            "mkldnn_available": torch.backends.mkldnn.is_available(),
            "mkldnn_enabled": runtime["mkldnn_enabled"],
        },
        "canonical_environment": {
            name: os.environ.get(name)
            for name in sorted(CANONICAL_EXECUTION_ENVIRONMENT)
        },
    }
    return observed


def full_hardware_runtime_fingerprint() -> dict[str, object]:
    """Return machine-readable evidence without unstable host/process identifiers."""
    runtime = canonical_cpu_runtime_fingerprint()
    observed = observed_runtime_and_hardware()
    semantic_identity = {
        "profile_version": runtime["profile_version"],
        "cpu_dispatch_capability": runtime["cpu_dispatch_capability"],
        "mkl_cbwr": runtime["MKL_CBWR"],
        "torch_version": torch.__version__,
        "torch_build_config_sha256": runtime["torch_build_config_sha256"],
        "execution_sentinel_sha256": runtime["execution_sentinel_sha256"],
        "canonical_environment": observed["canonical_environment"],
        "deterministic_algorithms_enabled": runtime[
            "deterministic_algorithms_enabled"
        ],
        "deterministic_warn_only_enabled": runtime[
            "deterministic_warn_only_enabled"
        ],
        "torch_num_threads": runtime["torch_num_threads"],
        "torch_num_interop_threads": runtime["torch_num_interop_threads"],
        "mkldnn_enabled": runtime["mkldnn_enabled"],
    }
    return {
        "fingerprint_version": HARDWARE_FINGERPRINT_VERSION,
        "semantic_execution_identity": semantic_identity,
        "semantic_execution_identity_sha256": _sha256_bytes(
            _canonical_json_bytes(semantic_identity)
        ),
        "observed_runtime_and_hardware": observed,
    }


def _assert_environment_preconfigured() -> None:
    for name, expected in CANONICAL_EXECUTION_ENVIRONMENT.items():
        actual = os.environ.get(name)
        if actual != expected:
            raise RuntimeError(f"CANONICAL_CPU_RUNTIME_ENV_MISMATCH:{name}")


def validate_canonical_cpu_runtime_fingerprint(
    fingerprint: dict[str, object],
) -> None:
    """Validate runtime/1.1 without accepting legacy runtime/1.0 semantics."""
    expected_values: dict[str, Any] = {
        "profile_version": CANONICAL_CPU_RUNTIME_VERSION,
        "deterministic_algorithms_enabled": True,
        "deterministic_warn_only_enabled": False,
        "torch_num_threads": 1,
        "torch_num_interop_threads": 1,
        "mkldnn_enabled": False,
        "cpu_dispatch_capability": "DEFAULT",
        "mkl_available": True,
        "openmp_available": True,
        "execution_sentinel_sha256": CANONICAL_EXECUTION_SENTINEL_SHA256,
        **CANONICAL_EXECUTION_ENVIRONMENT,
    }
    for name, expected in expected_values.items():
        if fingerprint.get(name) != expected:
            raise RuntimeError(
                f"CANONICAL_CPU_RUNTIME_PROFILE_DRIFT:{name}:"
                f"expected={expected}:actual={fingerprint.get(name)}"
            )


def _assert_canonical_profile() -> None:
    fingerprint = canonical_cpu_runtime_fingerprint()
    validate_canonical_cpu_runtime_fingerprint(fingerprint)
    build_configuration = _torch_build_configuration()
    required_build_markers = ("BLAS_INFO=mkl", "USE_MKL=ON", "USE_OPENMP=ON")
    for marker in required_build_markers:
        if marker not in build_configuration:
            raise RuntimeError(f"CANONICAL_CPU_RUNTIME_BUILD_UNSUPPORTED:{marker}")
    if torch.version.cuda is not None or not re.fullmatch(
        r"2\.12\.\d+\+cpu", torch.__version__
    ):
        raise RuntimeError("CANONICAL_CPU_RUNTIME_TORCH_BUILD_UNSUPPORTED")


def configure_canonical_cpu_runtime(seed: int | None = None) -> dict[str, object]:
    """Configure runtime/1.1 exactly once and optionally reset all supported RNGs."""
    global _CONFIGURED
    with _CONFIGURATION_LOCK:
        if not _CONFIGURED:
            _assert_environment_preconfigured()
            torch.use_deterministic_algorithms(True, warn_only=False)
            torch.set_num_threads(1)
            try:
                torch.set_num_interop_threads(1)
            except RuntimeError as error:
                raise RuntimeError("CANONICAL_CPU_RUNTIME_CONFIGURATION_LATE") from error
            torch.backends.mkldnn.enabled = False
            _CONFIGURED = True
        _assert_canonical_profile()
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
    return canonical_cpu_runtime_fingerprint()
