"""Frozen arm identifiers from work-planner/1.13 and Stage 1 runbook v2.13."""

from enum import StrEnum


class Arm(StrEnum):
    """Planner-only, interface, end-to-end and exploratory arms."""

    PLANNER_A1_RAW = "PLANNER_A1_RAW"
    PLANNER_A2_RAW = "PLANNER_A2_RAW"
    PLANNER_A2B_RAW = "PLANNER_A2B_RAW"
    PLANNER_A2C_RAW = "PLANNER_A2C_RAW"
    PLANNER_A3_RAW = "PLANNER_A3_RAW"
    PLANNER_A4_RAW = "PLANNER_A4_RAW"
    PLANNER_A5_RAW = "PLANNER_A5_RAW"

    I0_EQUAL_TOKENS_RAW = "I0_EQUAL_TOKENS_RAW"
    I1_ORACLE_CURRENT_RAW = "I1_ORACLE_CURRENT_RAW"
    I2_SHUFFLED_RAW = "I2_SHUFFLED_RAW"
    I3_PLANNER_CURRENT_RAW = "I3_PLANNER_CURRENT_RAW"

    E0_EQUAL_TOKENS_RAW = "E0_EQUAL_TOKENS_RAW"
    E1_PLANNER_CURRENT_RAW = "E1_PLANNER_CURRENT_RAW"
    E2_SHUFFLED_RAW = "E2_SHUFFLED_RAW"
    E3_ORACLE_REPLAN_RAW = "E3_ORACLE_REPLAN_RAW"
    P_REPLAY_RAW = "P_REPLAY_RAW"

    E0_EQUAL_TOKENS_OPERATIONAL = "E0_EQUAL_TOKENS_OPERATIONAL"
    E1_PLANNER_CURRENT_OPERATIONAL = "E1_PLANNER_CURRENT_OPERATIONAL"
