"""Frozen arm identifiers from work-planner/1.21 and Stage 1 runbook v2.21."""

from enum import StrEnum


class Arm(StrEnum):
    """Planner-only, interface, full-plan end-to-end and exploratory arms."""

    PLANNER_A1_RAW = "PLANNER_A1_RAW"
    PLANNER_A2_RAW = "PLANNER_A2_RAW"
    PLANNER_A2B_RAW = "PLANNER_A2B_RAW"
    PLANNER_A2C_RAW = "PLANNER_A2C_RAW"
    PLANNER_A3_RAW = "PLANNER_A3_RAW"
    PLANNER_A3R_RAW = "PLANNER_A3R_RAW"
    PLANNER_A4_RAW = "PLANNER_A4_RAW"
    PLANNER_A5_RAW = "PLANNER_A5_RAW"

    I0_EQUAL_TOKENS_RAW = "I0_EQUAL_TOKENS_RAW"
    I1_ORACLE_CURRENT_RAW = "I1_ORACLE_CURRENT_RAW"
    I2_SHUFFLED_RAW = "I2_SHUFFLED_RAW"
    I3_PLANNER_CURRENT_RAW = "I3_PLANNER_CURRENT_RAW"

    E0_EQUAL_TOKENS_RAW = "E0_EQUAL_TOKENS_RAW"
    E1_A3_FULL_PLAN_RAW = "E1_A3_FULL_PLAN_RAW"
    E2_SHUFFLED_A3_FULL_PLAN_RAW = "E2_SHUFFLED_A3_FULL_PLAN_RAW"
    E3_A3R_RANDOM_CODE_FULL_PLAN_RAW = "E3_A3R_RANDOM_CODE_FULL_PLAN_RAW"
    E4_A2C_STRUCTURED_FULL_PLAN_RAW = "E4_A2C_STRUCTURED_FULL_PLAN_RAW"
    E5_SELF_PLAN_RAW = "E5_SELF_PLAN_RAW"
    P_FULL_PLAN_REPLAY_RAW = "P_FULL_PLAN_REPLAY_RAW"

    E0_EQUAL_TOKENS_OPERATIONAL = "E0_EQUAL_TOKENS_OPERATIONAL"
    E1_A3_FULL_PLAN_OPERATIONAL = "E1_A3_FULL_PLAN_OPERATIONAL"
