"""Primary issue labels defined by work-planner/1.5."""

from enum import StrEnum


class ErrorType(StrEnum):
    SCHEMA_INVALID = "SCHEMA_INVALID"
    CONTRACT_VIOLATION = "CONTRACT_VIOLATION"
    HASH_MISMATCH = "HASH_MISMATCH"
    PARSE_FAILED = "PARSE_FAILED"
    UNKNOWN_REF = "UNKNOWN_REF"
    AMBIGUOUS_REF = "AMBIGUOUS_REF"
    WRONG_ARG_COUNT = "WRONG_ARG_COUNT"
    INVALID_ACTION = "INVALID_ACTION"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    SEMANTIC_UNRESOLVED = "SEMANTIC_UNRESOLVED"
    PLANNER_OOD_STATE = "PLANNER_OOD_STATE"
    CONTROL_UNAVAILABLE = "CONTROL_UNAVAILABLE"
    PROMPT_BUDGET_EXCEEDED = "PROMPT_BUDGET_EXCEEDED"
    HORIZON_EXCEEDED = "HORIZON_EXCEEDED"
    GOAL_NOT_REACHED = "GOAL_NOT_REACHED"
    PLANNER_FAILED = "PLANNER_FAILED"
    LLM_TIMEOUT = "LLM_TIMEOUT"
    EXECUTOR_FAILED = "EXECUTOR_FAILED"
    RUNNER_FAILED = "RUNNER_FAILED"
    INCOMPLETE_PAIR = "INCOMPLETE_PAIR"
    INVALID_RUN = "INVALID_RUN"
